stages: 
  run_full_pipeline: 
    cmd: python src/full_pipeline.py data/zomato_df_final_data.csv results models 
    deps: 
      - src/full_pipeline.py 
      - data/zomato_df_final_data.csv 
    outs: 
      - results 
      - models 
